# ================================================================
#   INTELLIGENT SYSTEM — AURORA SIGER COLONY
#   Mission: Manage energy, make decisions and predict consumption
#   Authors:  Carlos Eugênio Rodrigues de Andrade Filho — rm570285
#             Matheus Fuchelberguer Neves - rm571321
# ================================================================

# ----------------------------------------------------------------
# MODULE 1 — DATA STRUCTURES
# Colony data organized in dictionaries (key-value pairs) and
# lists, with hierarchy: colony → systems → subsystems
# ----------------------------------------------------------------

def inicializar_colonia(bateria=65, solar=40, eolico=20,
                         consumo=70, reserva=10,
                         vento=11, temp_interna=22, temp_externa=-60):
    """
    Creates and returns the main colony dictionary.
    Accepts parameters to make testing different scenarios easier.
    """
    colonia = {
        "nome": "Aurora Siger",
        "energia": {
            "bateria":        bateria,   # current charge level (%)
            "geracao_solar":  solar,     # units generated by solar panels
            "geracao_eolica": eolico,    # units generated by wind turbines
            "consumo_total":  consumo,   # total units consumed
            "reserva":        reserva    # units stored in reserve
        },
        "clima": {
            "temperatura_interna": temp_interna,  # degrees Celsius
            "temperatura_externa": temp_externa,  # degrees Celsius
            "velocidade_vento":    vento          # m/s
        },
        # Hierarchy: energetico    → solar / eolico
        #            suporte_vida  → oxigenio / aquecimento / agua
        #            nao_essenciais → laboratorio / comunicacao_secundaria
        "sistemas": {
            "energetico": {
                "solar":  {"ativo": True, "geracao": solar},
                "eolico": {"ativo": True, "geracao": eolico}
            },
            "suporte_vida": {
                "oxigenio":    {"ativo": True, "consumo": 20},
                "aquecimento": {"ativo": True, "consumo": 15},
                "agua":        {"ativo": True, "consumo": 10}
            },
            "nao_essenciais": {
                "laboratorio":            {"ativo": True, "consumo": 15},
                "comunicacao_secundaria": {"ativo": True, "consumo": 10}
            }
        },
        # Historical data series used for linear regression
        "historico": {
            "vento":          [6,  8,  10, 12, 14],
            "energia_eolica": [15, 20, 25, 30, 35]
        },
        # Stores every decision made during the current cycle
        "log_decisoes": []
    }
    return colonia


# ----------------------------------------------------------------
# VISUAL HELPERS — progress bar and section separators
# ----------------------------------------------------------------

def barra(valor, maximo=100, largura=20, cheio="█", vazio="░"):
    """Returns a text-based progress bar proportional to the value."""
    valor = max(0, min(valor, maximo))           # clamp to valid range
    preenchido = int((valor / maximo) * largura)
    return cheio * preenchido + vazio * (largura - preenchido)


def cabecalho(titulo):
    """Prints a bordered section header."""
    linha = "─" * 52
    print(f"\n┌{linha}┐")
    print(f"│  {titulo:<50}│")
    print(f"└{linha}┘")


def separador():
    """Prints a light dotted separator line."""
    print("  " + "·" * 48)


# ----------------------------------------------------------------
# MODULE 2 — COLONY STATUS PANEL
# ----------------------------------------------------------------

def exibir_status(colonia):
    """Displays the current colony status with visual progress bars."""
    e = colonia["energia"]
    c = colonia["clima"]
    geracao_total = e["geracao_solar"] + e["geracao_eolica"]
    consumo       = e["consumo_total"]
    bat           = e["bateria"]

    # Determine battery level label based on charge percentage
    if bat < 20:
        nivel_bat = "⚠ CRÍTICO"
    elif bat < 50:
        nivel_bat = "⚠ BAIXO"
    elif bat < 80:
        nivel_bat = "OK"
    else:
        nivel_bat = "✔ ÓTIMO"

    cabecalho(f"PAINEL DA COLÔNIA — {colonia['nome']}")
    print()
    print(f"  🔋 Bateria   [{barra(bat)}] {bat:>3}%  ({nivel_bat})")
    print(f"  ⚡ Geração   [{barra(geracao_total, 100)}] {geracao_total:>3} u")
    print(f"  🔌 Consumo   [{barra(consumo, 100)}] {consumo:>3} u")
    print(f"  🗄  Reserva   [{barra(e['reserva'], 50, 20)}] {e['reserva']:>3} u  (máx 50)")
    separador()
    print(f"  ☀  Solar:    {e['geracao_solar']} u    |    Eólico: {e['geracao_eolica']} u")
    print(f"  🌡  Interna: {c['temperatura_interna']}°C  |    Externa: {c['temperatura_externa']}°C")
    print(f"  🌬  Vento:   {c['velocidade_vento']} m/s")
    separador()

    # Display all subsystems with active/inactive status
    print("  SISTEMAS:")
    for grupo, subsistemas in colonia["sistemas"].items():
        rotulo = grupo.replace("_", " ").upper()
        print(f"    [{rotulo}]")
        for nome, dados in subsistemas.items():
            icone = "✅" if dados["ativo"] else "❌"
            chave = "geracao" if "geracao" in dados else "consumo"
            print(f"      {icone} {nome:<30} {dados[chave]:>3} u")


# ----------------------------------------------------------------
# MODULE 3 — SIMPLE LINEAR REGRESSION (no external libraries)
# Fits y = a*x + b using the least squares method
# ----------------------------------------------------------------

def calcular_regressao(lista_x, lista_y):
    """
    Computes the slope (a) and intercept (b) of a best-fit line
    y = a*x + b using the ordinary least squares method.
    """
    n       = len(lista_x)
    soma_x  = sum(lista_x)
    soma_y  = sum(lista_y)
    soma_xy = sum(lista_x[i] * lista_y[i] for i in range(n))
    soma_x2 = sum(x ** 2 for x in lista_x)

    # Least squares formulas for slope and intercept
    a = (n * soma_xy - soma_x * soma_y) / (n * soma_x2 - soma_x ** 2)
    b = (soma_y - a * soma_x) / n
    return round(a, 4), round(b, 4)


def prever_energia_eolica(colonia, vento_novo):
    """
    Uses linear regression on historical data to estimate
    wind energy generation for a given wind speed input.
    """
    hist     = colonia["historico"]
    a, b     = calcular_regressao(hist["vento"], hist["energia_eolica"])
    previsao = round(a * vento_novo + b, 1)

    cabecalho("MÓDULO 2 — PREVISÃO DE ENERGIA EÓLICA")
    print()
    print(f"  Histórico de vento   : {hist['vento']}")
    print(f"  Histórico de energia : {hist['energia_eolica']}")
    separador()
    print(f"  Modelo ajustado  : energia = {a} × vento + ({b})")
    print(f"  Entrada          : vento = {vento_novo} m/s")
    print(f"  Previsão         : [{barra(previsao, 50)}] ≈ {previsao} u")

    # Log the prediction result for the final report
    colonia["log_decisoes"].append(
        f"Previsão eólica → vento = {vento_novo} m/s → energia ≈ {previsao} u"
    )
    return previsao


# ----------------------------------------------------------------
# MODULE 4 — ENERGY ANALYSIS
# Compares generation vs consumption and issues alerts or suggestions
# ----------------------------------------------------------------

def analisar_energia(colonia):
    """
    Evaluates the energy balance (generation - consumption) and
    logs the result for the final cycle report.
    Returns the energy balance (saldo).
    """
    e       = colonia["energia"]
    geracao = e["geracao_solar"] + e["geracao_eolica"]
    consumo = e["consumo_total"]
    reserva = e["reserva"]
    saldo   = geracao - consumo   # positive = surplus, negative = deficit

    cabecalho("MÓDULO 3 — ANÁLISE DE ENERGIA")
    print()
    print(f"  Geração total : {geracao:>5} u")
    print(f"  Consumo total : {consumo:>5} u")
    print(f"  Reserva       : {reserva:>5} u")
    print(f"  Saldo         : {saldo:>+5} u")
    separador()

    # Priority order: critical → alert → suggestion → ok
    if consumo > geracao + reserva:
        icone = "🔴"
        msg   = "ALERTA CRÍTICO: consumo supera geração + reserva!"
        acao  = "Ativar modo emergência imediatamente."
    elif consumo > geracao:
        icone = "🟠"
        msg   = "ALERTA: consumo maior que geração."
        acao  = "Usar reserva e reduzir sistemas não essenciais."
    elif saldo > 20:
        icone = "💡"
        msg   = "SUGESTÃO: energia excedente disponível."
        acao  = "Armazenar excedente nas baterias."
    else:
        icone = "✅"
        msg   = "STATUS OK: balanço energético equilibrado."
        acao  = "Manter operação normal."

    print(f"  {icone} {msg}")
    print(f"     Ação recomendada: {acao}")

    colonia["log_decisoes"].append(f"Análise energética → {msg}")
    return saldo


# ----------------------------------------------------------------
# MODULE 5 — DECISION LOGIC
# Priority-based rules — life support systems are NEVER shut down
# ----------------------------------------------------------------

def tomar_decisao(colonia):
    """
    Applies decision rules in order of priority:
      Rule 1 — Emergency : battery < 20% AND high consumption
      Rule 2 — Alert     : battery < 50%
      Rule 3 — Economy   : consumption > generation (battery ok)
      Rule 4 — Normal    : all parameters within expected range
    Life support systems are always kept active regardless of rules.
    """
    e            = colonia["energia"]
    bateria      = e["bateria"]
    geracao      = e["geracao_solar"] + e["geracao_eolica"]
    consumo      = e["consumo_total"]
    alto_consumo = consumo > geracao   # True if consumption exceeds generation
    nao_ess      = colonia["sistemas"]["nao_essenciais"]

    cabecalho("MÓDULO 4 — LÓGICA DE DECISÃO")
    print()
    print(f"  Bateria      : {bateria}%")
    print(f"  Geração      : {geracao} u")
    print(f"  Consumo      : {consumo} u")
    print(f"  Consumo alto : {'Sim' if alto_consumo else 'Não'}")
    separador()

    # ── Rule 1: critical emergency ───────────────────────────────
    if bateria < 20 and alto_consumo:
        print("  🔴 MODO EMERGÊNCIA ATIVADO")
        print("     Condição : bateria < 20% E consumo > geração")
        print("     Decisão  : manter APENAS sistemas de suporte à vida")
        for sistema in nao_ess:
            nao_ess[sistema]["ativo"] = False   # shut down all non-essential systems
        print("     ❌ Laboratório             → DESLIGADO")
        print("     ❌ Comunicação secundária  → DESLIGADA")
        print("     ✅ Oxigênio / Aquecimento / Água → MANTIDOS")
        decisao = "EMERGÊNCIA"

    # ── Rule 2: low battery ──────────────────────────────────────
    elif bateria < 50:
        print("  🟠 ALERTA — REDUZIR CONSUMO")
        print("     Condição : bateria < 50%")
        print("     Decisão  : desligar laboratório (maior consumidor não essencial)")
        nao_ess["laboratorio"]["ativo"] = False   # shut down highest non-essential consumer
        print("     ❌ Laboratório             → DESLIGADO")
        print("     ✅ Comunicação secundária  → MANTIDA")
        decisao = "REDUÇÃO DE CONSUMO"

    # ── Rule 3: consumption exceeds generation ───────────────────
    elif alto_consumo:
        print("  🟡 MODO ECONOMIA")
        print("     Condição : consumo > geração (bateria ainda ok)")
        print("     Decisão  : monitorar — reduzir opcionais se persistir")
        decisao = "MODO ECONOMIA"

    # ── Rule 4: all systems nominal ──────────────────────────────
    else:
        print("  🟢 OPERAÇÃO NORMAL")
        print("     Condição : todos os parâmetros dentro do esperado")
        print("     Decisão  : manter operação / considerar armazenar excedente")
        decisao = "OPERAÇÃO NORMAL"

    colonia["log_decisoes"].append(f"Decisão final → {decisao}")
    return colonia


# ----------------------------------------------------------------
# MODULE 6 — CYCLE REPORT
# Consolidates and displays all decisions made during the cycle
# ----------------------------------------------------------------

def exibir_relatorio(colonia):
    """Prints a summary of all logged decisions and key metrics."""
    e          = colonia["energia"]
    geracao    = e["geracao_solar"] + e["geracao_eolica"]

    # Energy efficiency: how much of consumption was covered by generation
    eficiencia = round((geracao / e["consumo_total"]) * 100, 1) if e["consumo_total"] else 0

    cabecalho("RELATÓRIO FINAL DO CICLO")
    print()
    for i, entrada in enumerate(colonia["log_decisoes"], 1):
        print(f"  {i}. {entrada}")
    separador()
    print(f"  📊 Eficiência energética do ciclo : {eficiencia}%")
    print(f"  🔋 Carga de bateria restante      : {e['bateria']}%")
    print()


# ----------------------------------------------------------------
# MAIN PROGRAM — runs the full analysis pipeline
# ----------------------------------------------------------------

def executar_sistema(interativo=False):
    """
    Runs the complete colony analysis cycle.
    Set interativo=True to enter custom values via the terminal.
    """
    print("\n" + "═" * 54)
    print("  🚀  SISTEMA INTELIGENTE — COLÔNIA AURORA SIGER")
    print("═" * 54)

    if interativo:
        # Prompt the user for real-time sensor readings
        print("\n  Informe os dados atuais da colônia:\n")
        bateria = float(input("    Bateria (%)           : "))
        solar   = float(input("    Geração solar (u)     : "))
        eolico  = float(input("    Geração eólica (u)    : "))
        consumo = float(input("    Consumo total (u)     : "))
        reserva = float(input("    Reserva (u)           : "))
        vento   = float(input("    Velocidade vento (m/s): "))
        colonia = inicializar_colonia(bateria, solar, eolico,
                                      consumo, reserva, vento)
    else:
        # Use default demonstration values
        colonia = inicializar_colonia()

    # ── Analysis pipeline ────────────────────────────────────────
    exibir_status(colonia)
    prever_energia_eolica(colonia, colonia["clima"]["velocidade_vento"])
    analisar_energia(colonia)
    tomar_decisao(colonia)
    exibir_relatorio(colonia)

    print("═" * 54)
    print("  ✔  Ciclo de análise concluído com sucesso.")
    print("═" * 54 + "\n")


# ── Entry point ──────────────────────────────────────────────────
if __name__ == "__main__":
    # Change to interativo=True to enter your own values
    executar_sistema(interativo=False)
